import Head from 'next/head'
import styles from '../styles/choose.module.css'

const data = {
  formInput: {
    address: {
    street: "19 Union Square West",
    unit: "",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    selected: false
    }
  },
  normalized: {
    address: {
    street: "19 Union Square West",
    unit: "12th floor",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    selected: false
    }
  }
};

const formatAddress = (address) => {
  const unit = address.unit ? `, ${address.unit}` : '';
  return (
    <>
      <span>{`${address.street}${unit}`}</span><br/>
      <span>{`${address.city}, ${address.state} ${address.postalCode}`}</span>
    </>
  );
};

const Choose = () => {
  const onChoose = (format) => {
    console.log(data[format].address);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Updater</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.description}>
          Which address do you want to use?
        </h2>

        <div className={styles.choose}>
          <div onClick={() => onChoose('normalized')}>
            <p className={styles.official}>Official USPS Address</p>
            {formatAddress(data.normalized.address)}
          </div>

          <div onClick={() => onChoose('formInput')}>
            <p className={styles.unrecognized}>Unrecognized Address</p>
            {formatAddress(data.formInput.address)}
          </div>
        </div>
      </main>
    </div>
  )
}

export default Choose;
