import Head from 'next/head'
import { useRouter } from 'next/router';
import { Button } from 'react-bootstrap'
import FormattedAddress from '/components/FormattedAddress';
import styles from '../styles/confirm.module.css'


const data = {
  formInput: {
    address: {
    street: "19 Union Square West",
    unit: "",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    selected: false
    }
  },
  normalized: {
    address: {
    street: "19 Union Square West",
    unit: "12th floor",
    state: "NY",
    city: "New York",
    postalCode: "10001",
    selected: false
    }
  }
};

const Confirm = () => {
  const router = useRouter();

  const onEdit = () => {
    router.push('/');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Updater</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.description}>
          Does this address look correct?
        </h2>

        <div className={styles.confirm}>
          <FormattedAddress address={data.normalized.address} />
        </div>

        <Button onClick={onEdit} className="p-3" variant="outline-primary" type="submit">
          Enter new address
        </Button>
      </main>
    </div>
  )
}

export default Confirm;
